### PR TITLE
Docs remove labeler refs 367

### PR DESCRIPTION
**Pull request by guenthermi**
There are still images and phrases in the documentation which refer to the labeler. This PR should remove them. Moreover I removed the inclusion of the ui in the MANIFEST.in and the labeler component in .github/labeler.yml

### CODE REVIEW

**Review by bwanglzu — APPROVED** [review]
LGTM!

**Comment by gmastrapas** [comment]
why is deploy-to-netlify skipped?

**Review by azayz — APPROVED** [review]

**Comment by azayz** [comment]
> why is deploy-to-netlify skipped?

I think it's related to this https://jinaai.slack.com/archives/C018QC78L84/p1644313961605119

**Comment by gmastrapas** [comment]
> > why is deploy-to-netlify skipped?
> 
> I think it's related to this https://jinaai.slack.com/archives/C018QC78L84/p1644313961605119

but the branch name does not have dots

**Review by gmastrapas — APPROVED** [review]
Looks good!

**Pull request merged**
