### PR TITLE
feat: custom tag key

### PR DESCRIPTION
**Pull request by florian-hoenicke**

### CODE REVIEW

**Review by gmastrapas — CHANGES_REQUESTED** [review]
PyTorch and PaddlePaddle tuners should also accept this argument, I think the Evaluator too

**Comment by florian-hoenicke** [comment]
> PyTorch and PaddlePaddle tuners should also accept this argument, I think the Evaluator too

Thanks. I will add it.

**Comment by numb3r3** [comment]
BTW, a preprocess function could also be applied to do this job. 

```
def preprocess(doc: Document)
    doc.tags['finetuner_tag'] = doc.tags['custom_tag']
    return doc
```

**Comment by bwanglzu** [comment]
@florian-hoenicke let's develop new features in `finetuner.fit`

**Comment by florian-hoenicke** [comment]
Okay, I'll move the pr

**Pull request closed without merging**
