### PR TITLE
refactor: deprecate cpu

### PR DESCRIPTION
**Pull request by LMMilliken**
In preparation of finetuner 0.7.0, this pr removed the `cpu` parameter from the `create_run` method

---

- [x] This PR references an open issue
- [x] I have added a line about this change to CHANGELOG

### CODE REVIEW

**Review by gmastrapas — COMMENTED** [review]
Do we use it in `finetuner.encode` too?

**Review by bwanglzu — CHANGES_REQUESTED** [review]
please also remove `notebook_login`. Do not merge it, we'll merge until 0.7.0. This will go together with self-hosted features.

**Comment by LMMilliken** [comment]
> Do we use it in `finetuner.encode` too?

All occurances of the cpu parameter have been removed

**Review by gmastrapas — APPROVED** [review]

**Review by bwanglzu — APPROVED** [review]
LGTM!

**Pull request merged**
