### PR TITLE
fix: `download_artifact` throws error

### PR DESCRIPTION
**Pull request by jupyterjazz**
Closes https://github.com/jina-ai/finetuner.fit/issues/232

### CODE REVIEW

**Review by gmastrapas — COMMENTED** [review]
So the problem was that we weren't deserializing?

**Comment by jupyterjazz** [comment]
> So the problem was that we weren't deserializing?

yeap

**Review by gmastrapas — APPROVED** [review]
Looks good!

**Review by jemmyshin — APPROVED** [review]

**Review by violenil — APPROVED** [review]
LGTM!

**Pull request merged**
