### PR TITLE
chore(labeler): add component for audio matches

### PR DESCRIPTION
**Pull request by Roshanjossey**

### CODE REVIEW

**Comment by hanxiao** [comment]
can you post a screenshot, if it makes sense then I will just merge

**Comment by Roshanjossey** [comment]
image

**Comment by Roshanjossey** [comment]
While Bo was reviewing, he found some problems. We'll put this in draft as we figure it out.

**Comment by bwanglzu** [comment]
please refer to [this](https://github.com/jina-ai/jina/issues/3874) ticket in core.

**Review by bwanglzu — APPROVED** [review]

**Pull request merged**
