### PR TITLE
chore: add example CSV files

### PR DESCRIPTION
**Pull request by LMMilliken**
This pr adds a folder containing several CSV files that are suitable to be uploaded to the JAC as data for a finetuning run.
It is worth noting the the file `image-text_or_image_example.csv` is suitable for both text-image and image-image tasks as each row can be interpreted as either a `image-text` pair (suitable for text-image) or a `image-label` pair (suitable for image-image)

---

- [ ] This PR references an open issue
- [x] I have added a line about this change to CHANGELOG

### CODE REVIEW

**Comment by LMMilliken** [comment]
The mesh-mesh example wont work on JAC at the moment, as they are not using the latest version of core, which is needed to support pointnet++

**Comment by LMMilliken** [comment]
> Can you rename folder to `data`?

the name 'data' is in one of our gitignore files, i have renamed to example_data instead

**Review by guenthermi — APPROVED** [review]
LGTM

**Comment by gmastrapas** [comment]
> > Can you rename folder to `data`?
> 
> the name 'data' is in one of our gitignore files, i have renamed to example_data instead

`datasets` then? I really dislike `_` names, especially in the root dir 🥲

**Pull request merged**
